### ISSUE TITLE
[Feature Request] Grid Flex

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#786]
I love the Grid system. However I think that can be better for the UX experience create a Grid layout that can be adjust of the viewport of the browser and adjust the number of element per row.

something like [devcast.co](http://devcast.co) (resize the browser). Just need a little of CSS and the power of [flexbox](http://css-tricks.com/snippets/css/a-guide-to-flexbox/). ([demo](http://codepen.io/HugoGiraudel/embed/3e86f7ea0ae954e541f0431fa20f04f1?height=400&type=result&href=3e86f7ea0ae954e541f0431fa20f04f1&user=HugoGiraudel&safe=true&slug-hash=3e86f7ea0ae954e541f0431fa20f04f1&default-tab=result&animations=run#result-box))

**Comment by jshimko** [comment]
That layout is already using flexbox.

https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-theme-hubble/lib/client/scss/modules/_posts.scss#L142

It would just be a matter of tweaking the existing css a little.  Would be a fairly easy pull request.  ;)

**Comment by jshimko** [comment]
Ok, challenge accepted.  ;)

If you change [these lines][1] to the following, you get pretty close to the behavior of your examples...

```scss
.posts-grid {
	display: flex;
	flex-wrap: wrap;

	.post {
		@include large {
			width: calc((100% - 20px)/3);
			margin-right: 10px;
			&:nth-of-type(3n) {
				margin-right: 0;
			}
		}
        @include medium {
            width: calc((100% - 20px)/2);
            margin-right: 10px;
            &:nth-of-type(2n) {
                margin-right: 0;
            }
        }
        @include small {
            width: 100%;
        }

// continued...
```

3 wide on desktop, 2 wide on medium screens, full width on a phone.

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-theme-hubble/lib/client/scss/modules/_posts.scss#L142-L154
